sonar.projectKey=corona-python
sonar.projectName=Corona Python
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=venv/**,.venv/**,__pycache__/**,helm/**,*.tgz,pip.conf
