sonar.projectKey=corona-python
sonar.projectName=Corona Python
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.version=3.11
sonar.exclusions=helm/**,**/__pycache__/**

