apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "corona-python"
        vault.hashicorp.com/agent-inject-secret-app-creds: "app-creds/data/corona-go"
        vault.hashicorp.com/agent-inject-template-app-creds: |
          {{`{{- with secret "app-creds/data/corona-go" -}}
          apiKey={{ .Data.data.apiKey }}
          externalServiceToken={{ .Data.data.externalServiceToken }}
          {{- end }}`}}
    spec:
      serviceAccountName: corona-python
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      hostAliases:
        - ip: "10.146.183.231"
          hostnames:
            - "vault.lab"
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: APP_VERSION
              value: "{{ .Values.image.tag }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 15
