image:
  repository: harbor.lab:8080/library/corona-python
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1
containerPort: 8080

service:
  type: NodePort
  port: 8080
  nodePort: 30083

imagePullSecret: harbor-cred

hpa:
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 70

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"

